# Array Creation : Conversion from other python structures

In [10]:
import numpy as np

In [11]:
# work with list

counts = np.array([
    [1,2,3,4,5],
    [6,7,8,9,0]
])
counts

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [18]:
# find type

counts.dtype

dtype('int32')

In [19]:
# find size 
counts.size

10

In [20]:
# slice

counts[0]

array([1, 2, 3, 4, 5])

In [34]:
cities[0:1]

# find mean

counts.mean()

# finst st.dv (standard devision)

counts.std()

2.8722813232690143

In [17]:
# first list iteam second postion values
cities[0][2] 

3

In [29]:
# work with tuple


numbers = np.array([(1,2,3,4),(1,2,3,4)])
numbers
numbers.dtype

dtype('int32')

In [31]:
numbers[0:1]

array([[1, 2, 3, 4]])

In [39]:
# find mean

numbers.mean()
print(numbers.mean())
# finst st.dv (standard devision)

print(numbers.std())

2.5
1.118033988749895
