In [3]:
# Inbuild function

import numpy as np

**Find diamension**

In [4]:
arr = np.array([
    (1,2,3,4),
    (4,3,2,1),
    (7,4,6,7)
])

arr

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [7, 4, 6, 7]])

In [5]:
arr.ndim

2

In [7]:
# diamension shape ,matrix
arr.shape

(3, 4)

In [9]:
# tolal element 
arr.size

12

In [10]:
# occupice of byte in menory
arr.itemsize

4

In [11]:
# concrate two array

arr1 = np.array([
    (1,2,3,4),
    (4,3,2,1),
    (7,4,6,7)
])

arr1

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [7, 4, 6, 7]])

In [15]:
# two way to concrate horizontal and vertical

# vertical
vrt = np.vstack((arr,arr1))
vrt

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [7, 4, 6, 7],
       [1, 2, 3, 4],
       [4, 3, 2, 1],
       [7, 4, 6, 7]])

In [19]:
# horizontal

hrt = np.hstack((arr,arr1))

hrt

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [4, 3, 2, 1, 4, 3, 2, 1],
       [7, 4, 6, 7, 7, 4, 6, 7]])

In [20]:
hrt

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [4, 3, 2, 1, 4, 3, 2, 1],
       [7, 4, 6, 7, 7, 4, 6, 7]])

In [22]:
# convert column into row

# Transpose

hrt.T

array([[1, 4, 7],
       [2, 3, 4],
       [3, 2, 6],
       [4, 1, 7],
       [1, 4, 7],
       [2, 3, 4],
       [3, 2, 6],
       [4, 1, 7]])